/**
 * Generated by orval v8.11.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: v1
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface RequestLogin {
  /** @nullable */
  username?: string | null;
  /** @nullable */
  password?: string | null;
}

export interface ResponeGetProfileLine {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  statusMessage?: string | null;
  /** @nullable */
  pictureUrl?: string | null;
  /** @nullable */
  email?: string | null;
}

export type GetApiCheckTokenParams = {
token?: string;
};

export const getMyAPI = (axiosInstance: AxiosInstance = axios) => {
const getApi = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api`,options
    );
  }

const postApiLogin = (
    requestLogin?: RequestLogin, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/Login`,
      requestLogin,options
    );
  }

const postApiLoginOauth = (
    responeGetProfileLine?: ResponeGetProfileLine, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/api/LoginOauth`,
      responeGetProfileLine,{
    ...options,}
    );
  }

const getApiCheckToken = (
    params?: GetApiCheckTokenParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/CheckToken`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

const getApiLineCallbackLogin = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/LineCallbackLogin`,options
    );
  }

const getApiMsADCallbackLogin = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/MsADCallbackLogin`,options
    );
  }

const getApiGetDataUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/GetDataUser`,options
    );
  }

const getApiGetDataAdmin = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/GetDataAdmin`,options
    );
  }

const getApiGetDataAny = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/api/GetDataAny`,options
    );
  }

return {getApi,postApiLogin,postApiLoginOauth,getApiCheckToken,getApiLineCallbackLogin,getApiMsADCallbackLogin,getApiGetDataUser,getApiGetDataAdmin,getApiGetDataAny}};
export type GetApiResult = AxiosResponse<void>
export type PostApiLoginResult = AxiosResponse<void>
export type PostApiLoginOauthResult = AxiosResponse<string>
export type GetApiCheckTokenResult = AxiosResponse<void>
export type GetApiLineCallbackLoginResult = AxiosResponse<void>
export type GetApiMsADCallbackLoginResult = AxiosResponse<void>
export type GetApiGetDataUserResult = AxiosResponse<void>
export type GetApiGetDataAdminResult = AxiosResponse<void>
export type GetApiGetDataAnyResult = AxiosResponse<void>
